apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
spec:
  project: default
  source:
    chart: odoo
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{.Values.odoo.version}}
    helm:
      releaseName: odoo
      parameters:
        {{- range $name, $value := .Values.odoo.parameters }}
        - name: {{ $name }}
          value: {{ $value}}
        {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{.Values.odoo.namespace}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true