{{ if .Values.postgres.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{.Values.postgres.version}}
    helm:
      releaseName: postgres
      parameters:
        - name: auth.username
          value: odoouser
        - name: auth.password
          value: odoo
        - name: auth.password
          value: odoo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.postgres.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
