{{ if .Values.vaultwarden.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vaultwarden
    repoURL: https://gissilabs.github.io/charts/
    targetRevision: {{ .Values.vaultwarden.version }}
    helm:
      releaseName: vaultwarden
      parameters:
        {{- range $name, $value := .Values.vaultwarden.parameters }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{.Values.vaultwarden.namespace}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
